feat: used union types for data, loading, and error
ChristianAsilo/pokedex-async-redux pull request #15
Opened 2023-03-27 06:13 UTC by ChristianAsilo

- Added new actions for handling actionKey using before and after
- Removed PokemonDetails in GetPokemonAction
- Added new Async freezed file
- Modified PokemonOverviewVmFactory for waiting and error handling
- Modified PokemonOverviewPage to used union type

![analyze](https://user-images.githubusercontent.com/128013689/227855668-02727676-a95a-49c7-b6d1-e6e9743e05a2.PNG)
![format](https://user-images.githubusercontent.com/128013689/227855673-ee86c0a8-6147-43bc-9a01-a0ecfa77a9d4.PNG)
https://user-images.githubusercontent.com/128013689/227855286-ab935bc5-b0c6-426d-b58b-5d2e2671437d.mp4

2023-03-27 06:44 UTC, shawn-ffufm commented on lib/state/action/pokemon_actions.dart
> -class GetPokemonDetailsAction extends ReduxAction<AppState> {
why removed this one? you only need to update GetPokemonsAction right? 😱

2023-03-27 06:44 UTC, shawn-ffufm commented on lib/state/action/actions.dart
> +abstract class LoadingAction extends ReduxAction<AppState> {
you forgot to add a concise documentation 😝

remember, this is mandtoy right? 😉

2023-03-27 06:44 UTC, shawn-ffufm commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +        error: (errorMessage) => AlertDialog(
this seems not the proper way of calling the alert dialog 🙂

https://api.flutter.dev/flutter/material/AlertDialog-class.html

2023-03-27 06:44 UTC, shawn-ffufm commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +                pokemon: pokemon,
no need for extra trailing comma here 🙂

2023-03-27 06:45 UTC, shawn-ffufm commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +      home: pokemons.when(
have this for the body property not home 🙂

2023-03-27 06:45 UTC, shawn-ffufm requested changes
see pr feedback 🙂

2023-03-27 10:00 UTC, shawn-ffufm commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +    void _showErrorMessageSnackbar(String? errorMessage) {
tho this is allowed, please don't make it a practice to create a function inside a function unless it's super needed 🙂

have this outside then make it private instead 🙂

2023-03-27 10:00 UTC, shawn-ffufm commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +        content: Text(errorMessage!),
use null coalescing and use emptyString constant as its fallback value instead of using non-null enforce here to be safer 🙂

2023-03-27 10:00 UTC, shawn-ffufm commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +      key.currentState?.showSnackBar(snackBar);
seems no need for this, just use `ScaffoldMessenger.of(context).showSnackBar(SnackBar);`

2023-03-27 10:00 UTC, shawn-ffufm commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +        scaffoldMessengerKey: key,
seems no need for this

2023-03-27 10:00 UTC, shawn-ffufm commented on lib/state/action/actions.dart
> +//Loading action
this is a comment not a documentation, it should be ///. Also the message doesn't tell anything what this comment is for 😝

2023-03-27 10:00 UTC, shawn-ffufm commented on lib/state/action/pokemon_actions.dart
> -  GetPokemonDetailsAction({required this.pokemonName});
any reason why u've changed this one? 🤔

2023-03-27 10:00 UTC, shawn-ffufm commented on lib/utils/constants.dart
> +final key = GlobalKey<ScaffoldMessengerState>();
see related feedback above about this 🙂

2023-03-27 10:01 UTC, shawn-ffufm requested changes
see pr feedback 🙂

2023-03-27 10:04 UTC, ChristianAsilo commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +    void _showErrorMessageSnackbar(String? errorMessage) {
noted po sir

2023-03-27 11:21 UTC, ChristianAsilo commented on lib/state/action/pokemon_actions.dart
> -  GetPokemonDetailsAction({required this.pokemonName});
sorry po sir nagkamali lang po ako nag error po kasi then akala ko po is ireremove na based po doon sa pokemon_action nyo :sweat_smile:

2023-03-27 11:23 UTC, shawn-ffufm commented on lib/features/pokemon_overview/pokemon_overview_page.dart
> +        body: Builder(
why wrap this in a Builder? seems no need for this u can maximize using the build method's provided context 🙂

2023-03-27 11:23 UTC, shawn-ffufm commented on lib/state/action/pokemon_actions.dart
> -  GetPokemonDetailsAction({required this.pokemonName});
any update on this one? 🙂

2023-03-27 11:24 UTC, shawn-ffufm commented on lib/state/action/pokemon_actions.dart
> +  GetPokemonDetailsAction(this.pokemonName);
see my feedback at the left side of this 🙂

2023-03-27 11:24 UTC, shawn-ffufm requested changes
see minor pr feedback 🙂

2023-03-28 01:01 UTC, shawn-ffufm approved these changes

2023-03-28 01:01 UTC, merged